envs:
- OLA_JKS_URL: https://spyne-static.s3.amazonaws.com/Android/jks/ola.jks
  opts:
    is_expand: false
- OLA_KEYSTORE_PASSWORD: ola@123
  opts:
    is_expand: false
- OLA_ALLIES_KEY: Ola
  opts:
    is_expand: false
