package com.spyneai.posthog

object Events {

    val PROJECT_SUBMISSION_SKIPPED= "PROJECT_SUBMISSION_SKIPPED"
    val ALL_PROJECTS_SUBMITTED_BREAKS = "ALL_PROJECTS_SUBMITTED_BREAKS"
    val SINGLE_IMAGE_CAPTURED = "SINGLE_IMAGE_CAPTURED"
    val PROJECT_SUBMITTED = "PROJECT_SUBMITTED"
    val PROJECT_SUBMISSION_FAILED = "PROJECT_SUBMISSION_FAILED"
    val PROJECT_SUBMISSION_INTIATED = "PROJECT_SUBMISSION_INTIATED"
    val SUBMIT_PROJECT_STARTED = "SUBMIT_PROJECT_STARTED"
    val ALL_SKU_PROCESSED_BREAK = "ALL_SKU_PROCESSED_BREAK"
    val VIDEO_COMPRESSION_SUCCESS = "VIDEO COMPRESSION SUCCESS"
    val VIDEO_COMPRESSION_PROGRESS = "VIDEO COMPRESSION PROGRESS"
    val VIDEO_COMPRESSION_START = "VIDEO COMPRESSION START"
    val VIDEO_COMPRESSION_FAIL = "VIDEO COMPRESSION FAIL"
    val VIDEO_COMPRESSION_CANCEL = "VIDEO COMPRESSION CANCELED"
    val VIDEO_COMPRESSED_EXCEPTION = "VIDEO COMPRESSION EXCEPTION"
    val VIDEO_CONTENT_URI_CREATED = "VIDEO CONTENT URI CREATED"
    val VIDEO_CONTENT_URI_CREATION_FAIL = "VIDEO CONTENT URI CREATION FAIL"
    val VIDEO_FILE_NOT_EXIST = "VIDEO FILE NOT EXIST"


    val SKU_DATA_SEND_STARTED = "SKU_DATA_SEND_STARTED"
    val SKU_DATA_NOT_SENT = "SKU_DATA_NOT_SENT"

    val PROJECT_BODY = "PROJECT_BODY"
    val IMAGE_COMPRESSED = "IMAGE_COMPRESSED"
    val IMAGE_COMPRESSED_EXCEPTION = "IMAGE_COMPRESSED_EXCEPTION"
    val EXTERIOR_IMAGE_COMPRESSED = "EXTERIOR_IMAGE_COMPRESSED"
    val EXTERIOR_IMAGE_COMPRESSED_EXCEPTION = "EXTERIOR_IMAGE_COMPRESSED_EXCEPTION"

    val VIDEO_SELECTED = "VIDEO_SELECTED"

    val SKU_DATA_SENT = "SKU_DATA_SENT"
    val IS_SKU_DATA_SENT = "IS_SKU_DATA_SENT"
    val SKU_REAED_FINISHED = "SKU_REAED_FINISHED"
    val SKU_DATA_SENT_FAILED = "SKU_DATA_SENT_FAILED"
    val SKU_LOCAL_REAED_FINISHED = "SKU_LOCAL_REAED_FINISHED"

    //on Boarding
    val SLIDE_CHANGE = "Android On Boarding Slide Changed"

    //Signup
    val SIGNUP_INTIATED = "Android Signup Initiated"
    val SIGNUP_SUCCEED = "Android Signup Succeed"
    val SIGNUP_FAILED = "Android Signup Failed"

    //Login with password
    val LOGIN_INTIATED = "Android Login Initiated"
    val LOGIN_SUCCEED = "Android Login Succeed"
    val LOGIN_FAILED = "Android Login Failed"


    //login with otp
    val OTP_LOGIN_INTIATED = "Android OTP Login Initiated"
    val LOGIN_WITH_PASSWORD_INTIATED = "Android Login with password Initiated"
    val OTP_LOGIN_SUCCEED = "Android OTP Login Succeed"
    val OTP_LOGIN_FAILED = "Android OTP Login Failed"

    // otp verification & resend otp
    val OTP_VERIFICATION_INITIATED = "Android OTP Verification Initiated"
    val OTP_VERIFIED = "Android OTP Verified"
    val LOGIN_WITH_PASSWORD_SUCCESSED = "Android login with password successed"
    val OTP_VERIFICATION_FAILED = "Android OTP Verification Failed"
    val OTP_RESEND_INITIATED = "Android OTP Resend Initiated"
    val OTP_RESENT = "Android OTP Resent"
    val OTP_RESENT_FAILED = "Android OTP Resent Failed"

    //forgot password
    val FORGOT_PASSWORD_INTIATED = "Android Forgot Password Initiated"
    val FORGOT_PASSWORD_MAIL_SENT = "Android Forgot Password Mail Sent"
    val FORGOT_PASSWORD_FAILED = "Android Forgot Password Failed"

    //home
    val GOT_CATEGORIES = "Android Got Categories"
    val GET_CATEGORIES_FAILED = "Android Get Categories Failed"

    val GOT_ONGOING_ORDERS = "Android Got Ongoing Orders"
    val GET_ONGOING_ORDERS_FAILED = "Android Get Ongoing Orders Failed"

    val GET_COMPLETED_ORDERS = "Android Got Completed Orders"
    val GET_COMPLETED_ORDERS_FAILED = "Android Get Completed Orders Failed"

    //wallet
    val FETCH_CREDITS = "Android Credits Fetched"
    val FETCH_CREDITS_FAILED = "Android Credits Fetch Failed"

    //logout
    val LOG_OUT = "Android Log Out"

    //shoot
    val SHOW_HINT = "Android Show Hint"
    val SHOW_SHADOW_DIALOG = "Android Show Choose Shadow Dialog"
    val CREATE_PROJECT = "Android Create Project"
    val CREATE_PROJECT_FAILED = "Android Create Project Failed"
    val GET_LOCATIONS_FAILED = "Android Get Locations Failed"
    val SKU_PROCESS_STATE_WITH_SHADOW_FAILED = "Android SkuProcessStateWithShadow failed"
    val GET_SUBCATEGORIES = "Android Got Subcategories"
    val GET_SUBCATRGORIES_FAILED = "Android Get Subcategories Failed"
    val GET_OVERLAYS_INTIATED = "Android Get Overlays Initiated"
    val GET_OVERLAYS = "Android Got Overlays"
    val GET_OVERLAYS_FAILED = "Android Get Overlays Failed"
    val CREATE_SKU = "Android Create SKU"
    val CREATE_SKU_FAILED = "Android Create SKU Failed"

    val VIDEO_SKU_UPDATED = "Video SKU Updated"
    val VIDEO_SKU_UPDATE_FAILED = "Video SKU update Failed"

    val IMAGE_CAPTURED = "Android Image Captured"
    val IMAGE_CAPRURE_FAILED = "Android Image Capture Failed"
    val CONFIRMED = "Android Confirmed"
    val RESHOOT = "Android Reshoot"
    val GET_BACKGROUND = "Android Got Background"
    val TOTAL_FRAMES_UPDATED = "Android Total Frames Updated"
    val TOTAL_FRAMES_UPDATE_FAILED = "Android Total Frames Update Failed"
    val GET_BACKGROUND_FAILED = "Android Get Background Failed"
    val GET_MARKETPLACE_FAILED = "Android Get Marketplace Failed"
    val PROCESS_INITIATED = "Android Process Initiated"
    val PROCESS = "Android Process Completed"
    val PROCESS_FAILED = "Android Process Failed"



    //360
    val SHOW_360_HINT = "Show 360 Hint"
    val CREATE_360_PROJECT = "Create 360 Project"
    val CREATE_360_PROJECT_FAILED = "Create Project 360 Failed"
    val CREATE_360_SKU = "Create 360 SKU"
    val CREATE_360_SKU_FAILED = "Create SKU 360 Failed"

    val PROJECT_STATE_UPDATE_FAILED = "Android Project State Update Failed"
    val PROJECT_STATE_UPDATED = "Android Project State Updated"

    val OVERLAY_LOAD_FIALED = "Overlay Load Failed"
    val OVERLAY_CAMERA_FIALED = "Camera Failed"
    val OVERLAY_LOADED = "Overlay Loaded"

    val BLOCKED_WORKER_START_EXCEPTION = "START BLOCKED WORKER"
    val CANCELLED_WORKER_START_EXCEPTION = "START CANCELLED WORKER"

    val SERVICE_STARTED = "SERVICE STARTED"
    val SERVICE_START_EXCEPTION = "SERVICE START EXCEPTION"
    val VIDEO_SERVICE_STARTED = "VIDEO SERVICE STARTED"
    val SERVICE_ALREADY_RUNNING = "SERVICE ALREADY RUNNING"

    val JSON_RESPONSE = "JSON_RESPONSE"

    val GET_PRESIGNED_VIDEO_URL_FAILED = "GET PRESIGNED VIDEO_URL_FAILED"
    val GOT_PRESIGNED_VIDEO_URL = "GOT PRESIGNED VIDEO URL"

    val VIDEO_UPLOADED_TO_GCP = "VIDEO UPLOADED TO GCP"
    val VIDEO_UPLOAD_TO_GCP_FAILED = "VIDEO UPLOAD TO GCP FAILED"

    val MARK_VIDEO_UPLOADED_FAILED = "MARK VIDEO UPLOADED FAILED"
    val MARKED_VIDEO_UPLOADED = "MARKED VIDEO UPLOADED"
    val IMAGE_UPLOADED_TO_GCP = "IMAGE UPLOADED TO GCP"
    val IMAGE_UPLOAD_TO_GCP_FAILED = "IMAGE UPLOAD TO GCP FAILED"
    val MARKED_IMAGE_UPLOADED = "MARKED IMAGE UPLOADED"
    val MARK_IMAGE_UPLOADED_FAILED = "MARK IMAGE UPLOADED FAILED"
    val GOT_PRESIGNED_IMAGE_URL = "GOT PRESIGNED IMAGE URL"

    val GET_PRESIGNED_FAILED = "GET_PRESIGNED_FAILED"

    val MAX_RETRY = "MAX_RETRY"

    val UPLOADING_TO_GCP_INITIATED = "UPLOADING_TO_GCP_INITIATED"
    val IS_PRESIGNED_URL_UPDATED = "IS_PRESIGNED_URL_UPDATED"
    val IS_MARK_GCP_UPLOADED_UPDATED = "IS_MARK_GCP_UPLOADED_UPDATED"
    val IS_MARK_DONE_STATUS_UPDATED = "IS_MARK_DONE_STATUS_UPDATED"

    val GOT_VERSION = "GOT_VERSION"
    val APP_VERSION_FAIL = "APP_VERSION_FAIL"

    val VIDEO_NOT_UPLOADED = "VIDEO_NOT_UPLOADED"
    val VIDEO_UPLOADING_TO_GCP_INITIATED = "VIDEO_UPLOADING_TO_GCP_INITIATED"
    val IS_VIDEO_PRESIGNED_URL_UPDATED = "IS_VIDEO_PRESIGNED_URL_UPDATED"
    val IS_VIDEO_MARK_DONE_STATUS_UPDATED = "IS_VIDEO_MARK_DONE_STATUS_UPDATED"
    val IS_MARK_VIDEO_GCP_UPLOADED_UPDATED = "IS_MARK_VIDEO_GCP_UPLOADED_UPDATED"
    val IMAGE_ROTATION_EXCEPTION = "IMAGE_ROTATION_EXCEPTION"
    val INTERNET_CONNECTED = "INTERNET_CONNECTED"
    val INTERNET_DISCONNECTED = "INTERNET_DISCONNECTED"

    //get countries
    val GETCOUNTRIES_INTIATED = "GetCountries Initiated"
    val GETCOUNTRIES_SUCCEED = "GetCountries Succeed"
    val GETCOUNTRIES_FAILED = "GetCountries Failed"

    //google signup
    val GOOGLESIGNUP_INTIATED = "Google signup Initiated"
    val GOOGLESIGNUP_SUCCEED = "Google signup Succeed"
    val GOOGLESIGNUP_FAILED = "Google signup Failed"


    val CHECKIN_CALL_INTIATED="CHECKIN_CALL_INTIATED"
    val CHECKOUT_CALL_INTIATED="CHECKOUT_CALL_INTIATED"
    val CHECKIN_SUCCESS="CHECKIN_SUCCESS"
    val CHECKIN_FAILURE="CHECKIN_FAILURE"
    val CHECKOUT_SUCCESS="CHECKOUT_SUCCESS"
    val CHECKOUT_FAILURE="CHECKOUT_FAILURE"
    val SITEIMAGE_UPLOAD_RETRY="SITEIMAGE_UPLOAD_RETRY"
    val GET_LOCATION_SUCCESS_CHECKIN="GET_LOCATION_SUCCESS_CHECKIN"
    val GET_LOCATION_FAIL_CHECKIN="GET_LOCATION_FAIL_CHECKIN"
    val GET_LOCATION_SUCCESS_CHECKOUT="GET_LOCATION_SUCCESS_CHECKOUT"
    val GET_LOCATION_FAIL_CHECKOUT="GET_LOCATION_FAIL_CHECKOUT"
    val SITEIMAGE_UPLOADED_FAIL="SITEIMAGE_UPLOADED_FAIL"
    val EXTERIORIMAGE_ONEDGE_UPLOADED_FAIL="EXTERIORIMAGE_ONEDGE_UPLOADED_FAIL"
    val EXTERIORIMAGE_ONEDGE_UPLOADED="EXTERIORIMAGE_ONEDGE_UPLOADED"

    val GET_LOCATION_RETRY="SITEIMAGE_UPLOADED"
    val SITEIMAGE_UPLOADED="SITEIMAGE_UPLOADED"

    val GET_PRESIGNED_CALL_INITIATED = "GET_PRESIGNED_CALL_INITIATED"

    val MARK_DONE_CALL_INITIATED = "MARK_DONE_CALL_INITIATED"

    //data sync events
    val PROJECT_SYNC_TRIGGERED = "PROJECT_SYNC_PARENT_TRIGGERED"
    val PROJECT_SYNC_STARTED = "PROJECT_SYNC_STARTED"


    val PROJECT_CONNECTION_BREAK = "PROJECT_CONNECTION_BREAK"
    val ALL_PROJECTS_CREATED_BREAKS = "ALL_PROJECTS_CREATED_BREAKS"
    val SELECTED_PROJECT = "SELECTED_PROJECT"
    val PROJECTED_SKIPPED = "PROJECTED_SKIPPED"
    val CREATE_PROJECT_INITIATED = "CREATE_PROJECT_INITIATED"
    val PROJECT_CREATED = "PROJECT_CREATED"
    val PROJECT_DB_UPDATE = "PROJECT_DB_UPDATE"

    val PROCESS_SKU_PARENT_TRIGGERED = "PROCESS_SKU_PARENT_TRIGGERED"
    val PROCESS_SKU_STARTED = "PROCESS_SKU_STARTED"
    val SKU_SELECTED = "SKU_SELECTED"
    val SKU_SKIPPED = "SKU_SKIPPED"
    val UPDATE_TOTAL_FRAMES_INITIATED = "UPDATE_TOTAL_FRAMES_INITIATED"
    val UPDATE_TOTAL_FRAMES_FAILED = "UPDATE_TOTAL_FRAMES_FAILED"
    val SKU_TOTAL_FRAMES_UPDATED = "SKU_TOTAL_FRAMES_UPDATED"
    val SKU_TOTAL_FRAMES_IN_DB_UPDATED = "SKU_TOTAL_FRAMES_IN_DB_UPDATED"
    val PROCESS_SKU_INTIATED = "PROCESS_SKU_INTIATED"
    val PROCESS_SKU_FAILED = "PROCESS_SKU_FAILED"
    val SKU_PROCESSED = "SKU_PROCESSED"
    val SKU_PROCESSED_IN_DB_UPDATED = "SKU_PROCESSED_IN_DB_UPDATED"
    val PROCESS_SKU_CONNECTION_CONNECTION_BREAK = "PROCESS_SKU_CONNECTION_CONNECTION_BREAK"
    val ALL_SKUS_PROCESSED_BREAKS = "ALL_SKUS_PROCESSED_BREAKS"

    val VIDEO_ID_NULL = "VIDEO_ID_NULL"
    val VIDEO_MAX_RETRY = "VIDEO_MAX_RETRY"
    val ALL_VIDEO_UPLOADED_BREAK = "ALL_VIDEO_UPLOADED_BREAK"
    val VIDEO_CONNECTION_BREAK = "VIDEO_CONNECTION_BREAK"
    val VIDEO_UPLOAD_PARENT_TRIGGERED: String = "VIDEO_UPLOAD_PARENT_TRIGGERED"

    val IMAGE_SERVICE_STOPPED_BREAK = "IMAGE_SERVICE_STOPPED_BREAK"
    val VIDEO_SERVICE_STOPPED_BREAK = "VIDEO_SERVICE_STOPPED_BREAK"
    val VIDEO_SERVICE_STOPPED = "VIDEO_SERVICE_STOPPED"
    val VIDEO_PROCESS_FAILED = "VIDEO_PROCESS_FAILED"
    val VIDEO_PROCESSED = "VIDEO_PROCESSED"
    val VIDEO_PROCESS_CALL_INITIATED = "VIDEO_PROCESS_CALL_INITIATED"
    val VIDEO_NOT_TRIMMED = "VIDEO_NOT_TRIMMED"
    val VIDEO_INVALID_TRIMMED = "VIDEO_INVALID_TRIMMED"
    val VIDEO_TRIMMED= "VIDEO_TRIMMED"
    val VIDEO_CAPTURE_FAILED= "VIDEO_CAPTURE_FAILED"
    val VIDEO_CAPTURED = "VIDEO_CAPTURED"
    val VIDEO_MARKED_UPLOADED = "VIDEO_MARKED_UPLOADED"
    val VIDEO_MARK_DONE_CALL_INITIATED = "VIDEO_MARK_DONE_CALL_INITIATED"
    val IS_VIDEO_GCP_UPLOADED_UPDATED = "IS_VIDEO_GCP_UPLOADED_UPDATED"
    val GOT_VIDEO_PRESIGNED_VIDEO_URL = "GOT_VIDEO_PRESIGNED_VIDEO_URL"
    val GET_VIDEO_PRESIGNED_FAILED = "GET_VIDEO_PRESIGNED_FAILED"
    val GET_VIDEO_PRESIGNED_CALL_INITIATED = "GET_VIDEO_PRESIGNED_CALL_INITIATED"


    val UPDATE_COMBO_SKU_INTIATED = "UPDATE_COMBO_SKU_INTIATED"
    val UPDATE_COMBO_SKU_FAILED = "UPDATE_COMBO_SKU_FAILED"
    val COMBO_SKU_UPDATED = "COMBO_SKU_UPDATED"
    val COMBO_SKU_DB_UPDATED = "COMBO_SKU_DB_UPDATED"

    val OLDEST_IMAGE = "OLDEST IMAGE"
    val OLDEST_VIDEO = "OLDEST VIDEO"
    val CREATE_PROJECT_PENDING = "CREATE_PROJECT_PENDING"
    val PROCESS_SKU_PENDING = "PROCESS_SKU_PENDING"

    val FOODSDKHOME_ONCREATE_SUCESS = "FOODSDKHOME_ONCREATE_SUCESS"

    val GET_VERSION_DETAILS_INIT = "GET_VERSION_DETAILS_INIT"
    val GET_VERSION_DETAILS_SUCESS = "GET_VERSION_DETAILS_SUCESS"
    val GET_VERSION_DETAILS_FAILED = "GET_VERSION_DETAILS_FAILED"

    val GET_RID_INIT = "GET_RID_INIT"
    val GET_RID_SUCESS = "GET_RID_SUCESS"
    val GET_RID_FAILED = "GET_RID_FAILED"

    val GET_USER_DETAILS_INIT = "GET_USER_DETAILS_INIT"
    val GET_USER_DETAILS_SUCESS = "GET_USER_DETAILS_SUCESS"
    val GET_USER_DETAILS_FAILED = "GET_USER_DETAILS_FAILED"

    val GOT_CATEGORIES_INIT = "GOT_CATEGORIES_INIT"


    // self serve
    val PROJECT_ADDED_TO_CART = "PROJECT_ADDED_TO_CART"
    val PROJECT_CREDIT_IMAGE_COUNT = "PROJECT_CREDIT_IMAGE_COUNT"

    val FETCH_OUTPUT_SKU = "FETCH_OUTPUT_SKU"
    val FETCH_OUTPUT_IMAGES_CALLED = "FETCH_OUTPUT_IMAGES_CALLED"
    val FETCH_OUTPUT_IMAGES_SUCESS = "FETCH_OUTPUT_IMAGES_SUCESS"
    val FETCH_OUTPUT_IMAGES_FAILED = "FETCH_OUTPUT_IMAGES_FAILED"
    val PING_OUTPUT_IMAGES = "PING_OUTPUT_IMAGES"
    val FETCH_USER_CREDITS_CALLED = "FETCH_USER_CREDITS"
    val FETCH_USER_CREDITS_SUCESS = "FETCH_USER_CREDITS_SUCESS"
    val FETCH_USER_CREDITS_FAILED = "FETCH_USER_CREDITS_FAILED"
    val FETCH_CART_PROJECT_IDS = "PING_OUTPUT_IMAGES"

    val CART_PROJECT_IDS = "CART_PROJECT_IDS"
    val PROJECT_REMOVED_FROM_CART = "PROJECT_REMOVED_FROM_CART"
    val GENERATE_ORDER_INIT = "GENERATE_ORDER_INIT"
    val GENERATE_ORDER_SUCESS = "GENERATE_ORDER_SUCESS"
    val GENERATE_ORDER_FAILED = "GENERATE_ORDER_FAILED"
    val PREPARE_CHECKOUT_INIT = "PREPARE_CHECKOUT_INIT"
    val PREPARE_CHECKOUT_EXCEPCTION = "PREPARE_CHECKOUT_EXCEPCTION"

    val IMAGE_DELETED = "IMAGE_DELETED"

    val HAVE_AN_ENTERPRISE_CODE_CLICKED = "HAVE_AN_ENTERPRISE_CODE_CLICKED"
    val CREATE_YOUR_ACCOUNT_CLICKED = "CREATE_YOUR_ACCOUNT_CLICKED"
    val SIGNIN_TO_YOUR_ACCOUNT_CLICKED = "SIGNIN_TO_YOUR_ACCOUNT_CLICKED"
    val LOGIN_WITH_PHONE_NUMBER_CLICKED = "LOGIN_WITH_PHONE_NUMBER_CLICKED"
    val LOGIN_WITH_EMAIL_CLICKED = "LOGIN_WITH_EMAIL_CLICKED"
    val LOGIN_WITH_GOOGLE_CLICKED = "LOGIN_WITH_GOOGLE_CLICKED"
    val FAB_CLICKED = "FAB_CLICKED"
    val CATEGORY_DROPDOWN_CLICKED = "CATEGORY_DROPDOWN_CLICKED"
    val CATEGORY_DROPDOWN_SELECTED = "CATEGORY_DROPDOWN_SELECTED"
}